packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - shadcn@4.11.1
